# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awt < Formula
  desc "Agent WorkTrees - Enable multiple AI agents to safely create, use, and hand off Git worktrees"
  homepage "https://github.com/kernel-labs-ai/awt"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kernel-labs-ai/awt/releases/download/v0.1.1/awt_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "67efc20b65c649e67ade9719867be81a955df3918e562e0231a43e0084cd7367"

      def install
        bin.install "awt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kernel-labs-ai/awt/releases/download/v0.1.1/awt_0.1.1_Darwin_arm64.tar.gz"
      sha256 "61380068e1bb5acb06ecfeba07af3427e784546365ff14f341c08118f803de26"

      def install
        bin.install "awt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kernel-labs-ai/awt/releases/download/v0.1.1/awt_0.1.1_Linux_x86_64.tar.gz"
      sha256 "dcf231416511c5e520bfffd5767803ae2d5db78b9ea1152e7ac59dada099d5c1"
      def install
        bin.install "awt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kernel-labs-ai/awt/releases/download/v0.1.1/awt_0.1.1_Linux_arm64.tar.gz"
      sha256 "94873a7c4ad1ab88caa8ea0f50c343fec65a84c31f03ccc557465d7b15bac9eb"
      def install
        bin.install "awt"
      end
    end
  end
end
