# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awt < Formula
  desc "Agent WorkTrees - Enable multiple AI agents to safely create, use, and hand off Git worktrees"
  homepage "https://github.com/kernel-labs-ai/awt"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kernel-labs-ai/awt/releases/download/v0.1.2/awt_0.1.2_Darwin_x86_64.tar.gz"
      sha256 "39fbc0eb981f23fdc5b9911ed97b02ece189f2febee1c3b6486329d8f9551019"

      def install
        bin.install "awt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kernel-labs-ai/awt/releases/download/v0.1.2/awt_0.1.2_Darwin_arm64.tar.gz"
      sha256 "ec5382a4e793f945690fdb4117a7def7dc43d28c0d350c574392c96d82bd42b3"

      def install
        bin.install "awt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kernel-labs-ai/awt/releases/download/v0.1.2/awt_0.1.2_Linux_x86_64.tar.gz"
      sha256 "0c21df2f6f7dc51d745dd8a32a8654b4111a934234fcb5053fcbb18fb932c2ed"
      def install
        bin.install "awt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kernel-labs-ai/awt/releases/download/v0.1.2/awt_0.1.2_Linux_arm64.tar.gz"
      sha256 "3cc23f59cb8ed13e93bbfdaeb217ac1c2e65c1a6ddfbdae023c05cc9f534af3c"
      def install
        bin.install "awt"
      end
    end
  end
end
