# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awt < Formula
  desc "Agent WorkTrees - Enable multiple AI agents to safely create, use, and hand off Git worktrees"
  homepage "https://github.com/kernel-labs-ai/awt"
  version "0.1.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kernel-labs-ai/awt/releases/download/v0.1.8/awt_0.1.8_Darwin_x86_64.tar.gz"
      sha256 "2059116d85c0e93376e517a220b423ae2765eab397c7648d9be4970807ef3325"

      def install
        bin.install "awt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kernel-labs-ai/awt/releases/download/v0.1.8/awt_0.1.8_Darwin_arm64.tar.gz"
      sha256 "79fae585bd39894b6ecc339148de461eb1e8cb2aa3fc80b3de343c56a0f2714c"

      def install
        bin.install "awt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kernel-labs-ai/awt/releases/download/v0.1.8/awt_0.1.8_Linux_x86_64.tar.gz"
      sha256 "ac6bb086d94987df687112807928dab5d06aaa44f2f313b618df532bbba91c68"
      def install
        bin.install "awt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kernel-labs-ai/awt/releases/download/v0.1.8/awt_0.1.8_Linux_arm64.tar.gz"
      sha256 "86cd9494b608409b45d2aab24484a578e32fddc9850a02aab482e836efbd4736"
      def install
        bin.install "awt"
      end
    end
  end
end
